//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iKandi.Web.Admin.OBAdmin {
    
    
    public partial class frmmanpowerattendance {
        
        /// <summary>
        /// rbtnAtteType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rbtnAtteType;
        
        /// <summary>
        /// Usermanpowerattendence1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iKandi.Web.UserControls.Forms.Usermanpowerattendence Usermanpowerattendence1;
        
        /// <summary>
        /// toolkit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
       
        
        /// <summary>
        /// frmuserOtattendence1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iKandi.Web.UserControls.Forms.frmuserOtattendence frmuserOtattendence1;
    }
}
